save_dir_root: './runs/run'

########################################
## Input graph settings
cache_dir: './.cached_pdists'

input_graph: '../data/btree364.edges.gz'

########################################
## Embedding settings
embedding:
  closure:
    name: graphembed.modules.ManifoldEmbedding
    params:
      manifolds:
        - object:
            name: graphembed.manifolds.SymmetricPositiveDefinite
            params:
              n: 2
              use_stein_div: False

########################################
## The objective
objective_fn:
  closure:
    name: graphembed.objectives.KLDiveregenceLoss
    params:
      inference_model: 'sne'
      inclusive: True

########################################
## Training settings
training_params:
  alpha: 10.0
  n_epochs: 1500
  batch_size: null
  stabilize_every_epochs: 20
  val_every_epochs: 50

embedding_optimizer:
  closure:
    name: graphembed.optim.RiemannianAdam
    params:
      lr: 0.01
      max_grad_norm: 100
      exact: False
